# Generated by Django 5.2.6 on 2025-10-04 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_subscription_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('first_date', models.DateField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, max_length=128, null=True)),
                ('average_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('predicted_next_date', models.DateField(blank=True, null=True)),
                ('last_user_modified_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=128, null=True)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='Account.subscription')),
            ],
        ),
    ]
