# Generated by Django 5.2.6 on 2025-10-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_subscriptiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetail',
            name='website_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
