# Generated by Django 5.2.6 on 2025-10-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_subscriptiondetail_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetail',
            name='transaction_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
