# Generated by Django 5.2.6 on 2025-11-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_subscriptiondetail_transaction_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetail',
            name='cancel_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondetail',
            name='reactivate_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
