# Generated by Django 5.2.6 on 2025-11-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_subscriptiondetail_cancel_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondetail',
            name='merchant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
